---
sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.3.0
gemfile:
  - gemfiles/Gemfile.rails-3.2
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-4.1
  - gemfiles/Gemfile.rails-5.0

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.0
    - rvm: 2.1.2
      gemfile: gemfiles/Gemfile.rails-5.0
